# Generated by Django 3.2.7 on 2021-10-12 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notasmusicas',
            old_name='aula',
            new_name='musica',
        ),
        migrations.AlterField(
            model_name='musicas',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.playlist'),
        ),
    ]
