# Generated by Django 3.2.7 on 2021-10-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20211012_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicas',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='playlist.playlist'),
        ),
    ]
